SearchSingleCase: Resuming 'TopPopRecommender' Failed, no such file exists.
SearchSingleCase: New best config found. Config 0: {} - results: PRECISION: 0.0192941, PRECISION_RECALL_MIN_DEN: 0.0431886, RECALL: 0.0421598, MAP: 0.0084287, MAP_MIN_DEN: 0.0187885, MRR: 0.0701739, NDCG: 0.0431270, F1: 0.0264730, HIT_RATE: 0.1600092, ARHR_ALL_HITS: 0.0767787, NOVELTY: 0.0032845, AVERAGE_POPULARITY: 0.5634275, DIVERSITY_MEAN_INTER_LIST: 0.1145416, DIVERSITY_HERFINDAHL: 0.9114539, COVERAGE_ITEM: 0.0010201, COVERAGE_ITEM_HIT: 0.0007753, ITEMS_IN_GT: 0.9612764, COVERAGE_USER: 0.9351414, COVERAGE_USER_HIT: 0.1496313, USERS_IN_GT: 0.9351414, DIVERSITY_GINI: 0.0004803, SHANNON_ENTROPY: 3.5816645, RATIO_DIVERSITY_HERFINDAHL: 0.9118792, RATIO_DIVERSITY_GINI: 0.0011016, RATIO_SHANNON_ENTROPY: 0.2718001, RATIO_AVERAGE_POPULARITY: 9.2160579, RATIO_NOVELTY: 0.3778107, 
SearchSingleCase: Config 0 Exception. Config: {} - Exception: Traceback (most recent call last):
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 495, in _objective_function
    result_df_test = self._evaluate_on_test(recommender_instance, current_fit_hyperparameters_dict,
  File "/home/ubuntu/RecSys-Challenge-2022-Polimi/HyperparameterTuning/SearchAbstractClass.py", line 392, in _evaluate_on_test
    result_string = get_result_string_df(result_df_test)
NameError: name 'get_result_string_df' is not defined

SearchSingleCase: Search complete. Best config is None: None
